# Generated by Django 4.1 on 2023-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
